title: "Objektorientierte Programmierung"
domain: "http://th-rosenheim.de"
email: marcel.tilly@th-rosenheim.de
description: "Materialien zum Pflichtmodul Objektorientiertes Programmieren (OOP)"
baseurl: ""
url: "https://hsro-wif-oop.github.io"
exclude:
  - "LICENSE"
  - "Remarks.md"
  - "*.plantuml"
  - examples
github_username: ["matworx"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #     span:
  #       line_numbers: false
  #     block:
  #       line_numbers: true
